#!/bin/bash

echo "=== ローカルテスト手順 ==="
echo ""
echo "【方法1: OpenAI APIでテスト（推奨）】"
echo ""
echo "1. .env ファイルを編集："
echo "   OPENAI_BASE_URL=https://api.openai.com/v1"
echo "   OPENAI_API_KEY=sk-your-actual-api-key"
echo ""
echo "2. サーバー起動："
echo "   python -m uvicorn main:app --reload --port 8000"
echo ""
echo "3. ブラウザでアクセス："
echo "   http://localhost:8000"
echo ""
echo "4. ログイン後、以下のような質問をしてテスト："
echo "   「発注固定費用が1000円、平均需要量が100個/日、"
echo "    在庫保管費用が1円/個/日、品切れ費用が100円/個/日の"
echo "    場合の経済発注量を計算してください」"
echo ""
echo "---"
echo ""
echo "【方法2: Ollama でテスト（Function Calling非対応）】"
echo ""
echo "Function Calling は動作しませんが、通常のチャットは可能です。"
echo ""
echo "1. Ollama起動確認："
echo "   curl http://localhost:11434/v1/models"
echo ""
echo "2. .env は現在のまま（Ollama設定）"
echo ""
echo "3. サーバー起動："
echo "   python -m uvicorn main:app --reload --port 8000"
echo ""
echo "====================================="
