# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/16case2.ipynb.

# %% auto 0
__all__ = ['folder', 'mapbox_access_token']

# %% ../nbs/16case2.ipynb 3
import sys
sys.path.append('..')
from scmopt.core import *
from scmopt.data import *
from scmopt.abc import *
from scmopt.lnd import *
from scmopt.metro import *
from scmopt.forecast import *
from scmopt.lotsizing import *
from scmopt.optinv import *
import scmopt.optseq as optseq
from scmopt.snd import *
import scmopt.shift as shift

import pickle
import colorlover as cl
from geopy.distance import great_circle as distance
import pickle
import numpy as np
import plotly.graph_objs as go
import plotly.express as px
import plotly
from pandas_profiling import ProfileReport
#from mypulp import GRB, quicksum, Model
from gurobipy import GRB, quicksum, Model
import chart_studio.plotly as py
import pandas as pd
import random
import string
import datetime
import math
import ast
from collections import OrderedDict, defaultdict
import networkx as nx
from IPython.display import Image, YouTubeVideo
#import seaborn as sns
from faker import Faker

from openpyxl import Workbook, load_workbook
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.chart import ScatterChart, Reference, Series
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import ColorScaleRule, CellIsRule, FormulaRule
from openpyxl.styles import Color, PatternFill, Font, Border, Alignment
from openpyxl.styles.borders import Border, Side
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.comments import Comment

folder = "../data/case2/"
mapbox_access_token = 'pk.eyJ1IjoibWlraW9rdWJvIiwiYSI6ImNqYXQ3dHBqdzR5ZGwyd3BkeG5rOTl0b2UifQ.1utsXNi2V-WdzfWlvCMj_A'
