# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/16case.ipynb.

# %% auto 0
__all__ = ['TEST', 'folder', 'mapbox_access_token']

# %% ../nbs/16case.ipynb 3
TEST = True
import sys
sys.path.append('..')
from scmopt.core import *
from scmopt.data import *
from scmopt.abc import *
from scmopt.lnd import *
from scmopt.metro import *
from scmopt.forecast import *
from scmopt.lotsizing import *
from scmopt.optinv import *
import scmopt.optseq as optseq
from scmopt.snd import *
import scmopt.shift as shift

import pickle
import colorlover as cl
from geopy.distance import great_circle as distance
import pickle
import numpy as np
import plotly.graph_objs as go
import plotly.express as px
import plotly
from pandas_profiling import ProfileReport
#from mypulp import GRB, quicksum, Model
from gurobipy import GRB, quicksum, Model
import chart_studio.plotly as py
import pandas as pd
import random
import string
import datetime
import math
import ast
from collections import OrderedDict, defaultdict
import networkx as nx
from IPython.display import Image, YouTubeVideo
#import seaborn as sns
from faker import Faker
#folder = "../data/"
folder = "../data/case/"
mapbox_access_token = 'pk.eyJ1IjoibWlraW9rdWJvIiwiYSI6ImNqYXQ3dHBqdzR5ZGwyd3BkeG5rOTl0b2UifQ.1utsXNi2V-WdzfWlvCMj_A'
