"""Use OpenAI, LangChain and LM Studio to develop LLMs for SC Optimization"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/20autogen.ipynb.

# %% auto 0
__all__ = ['opening_message', 'vrp_message', 'extract_vrp_info', 'extract_sc_models']

# %% ../nbs/20autogen.ipynb 108
from langchain.prompts import ChatPromptTemplate, PromptTemplate
from langchain.output_parsers import ResponseSchema
from langchain.output_parsers import StructuredOutputParser
from langchain_openai import ChatOpenAI, OpenAI

# %% ../nbs/20autogen.ipynb 110
def extract_vrp_info(user_message: str) -> str: 
    #Output Parser
    tw_schema = ResponseSchema(name="time windows", description="number of time windows", type="string")
    dimension_schema = ResponseSchema(name="dimensions", description="number of dimensions", type="string")
    skill_schema = ResponseSchema(name="skills", description="number of skills", type="string")
    break_schema = ResponseSchema(name="breaks", description="number of breaks the drivers of vehicles need to have", type="string")
    response_schemas = [tw_schema, dimension_schema, skill_schema, break_schema]
    
    output_parser = StructuredOutputParser.from_response_schemas(response_schemas)
    format_instructions = output_parser.get_format_instructions()

    template_string = """Extract the information of a vehicle routing prblem from the text \
    that is delimited by triple backticks.
        
    The information you need to extract are:
    
    - the number of time windows. 
    - the number dimension of the loads and the resource (vehicle) capacity. 
    - the number of skills that the loads and vehicles posess. 
    - the maximum number of breaks the drivers of vehicles need to have. 

    text: ```{text}```

    {format_instructions}
    """
    
    prompt_templete = ChatPromptTemplate.from_template(template=template_string)
    message = prompt_templete.format_messages(text=user_message, format_instructions=format_instructions)

    chat = OpenAI(temperature=0.1, base_url="http://localhost:1234/v1", api_key="not-needed", model="local-model")
    response = chat.invoke(message)
    result = output_parser.invoke(response)
    
    return result

# %% ../nbs/20autogen.ipynb 113
def extract_sc_models(user_message:str) -> str: 

    category_schema = ResponseSchema(name="category", description="category that user is interested in", type="float")
    confidense_schema = ResponseSchema(name="confidense", description="confidense prbability", type="float")
    response_schemas = [category_schema, confidense_schema]
    
    output_parser = StructuredOutputParser.from_response_schemas(response_schemas)
    format_instructions = output_parser.get_format_instructions()

    template_string = """ 
    You will be provided with customer queries. \
    The customer query will be delimited with #### characters.\
    
    Output a python list of objects, where each object has \
    the following format:
        'category': <one of Logistcs or Supply Chain Network Design, Vehicle Routing, \
        Inventory Planning and Optimization, \
        Production Scheduling, Demand Forecasting>,
    
    Each category has the following definition and keywords.
    The categories or keywards must be found in the customer query.
    
    Allowed categories: 
    
    Logistcs or Supply Chain Network Design:
    
    - definition: 
    A supply-chain network can be strategically designed in such a way as to \ 
    reduce the cost of the supply chain; it has been suggested by experts  |
    that 80% of supply chain costs are determined by location of facilities and the flow of product \
    between the facilities. \
    Supply chain network design is sometimes referred to as 'Network Modelling', \ 
    due to the fact a mathematical model can be created to optimize the supply-chain network. \
    Companies have been led to modify their basic supply chain,  \ 
    investing in the tools and resources to develop an improved SCN \ 
    design that takes into account taxation regulations, new entrants  \
    into their industry and availability of resources, has resulted in more complex network designs. \
    Designing a SCN involves creating a network that incorporates all the facilities,  \ 
    means of production, products, and transportation assets owned by the organization \ 
    or those not owned by the organization but which immediately support the supply-chain  \ 
    operations and product flow. The design should also include details of the number and \ 
    location of facilities: plants, warehouses, and supplier base. 
    
    - keywards: facility, location, relocation, assignment of product, long-term decision, strategic level
    
    Vehicle Routing:
    
    - definition: 
    The VRP concerns the service of a delivery company. \
    How things are delivered from one or more depots which has a given set of home vehicles \
    and operated by a set of drivers who can move on a given road network to a set of customers. \
    It asks for a determination of a set of routes, S, (one route for each vehicle that must \
    start and finish at its own depot) such that all customers' requirements and operational \
    constraints are satisfied and the global transportation cost is minimized.  \
    This cost may be monetary, distance or otherwise.
    
    - keywards: vehicle, truck, milkrun, time windows, ship, transportation, backhaul, \ 
    routing, operational, short-term decision
    
    Inventory Planning:
    
    - keywards: inventory, shelf, safet stock, cycle stock, allocation, \
      operational and tactical, mid-term decision
    
    Production Scheduling:
    
    - keywards: plant, scheduling, lot-size, sequence, resource assignment, operational and tactical, mid-term decision
    
    Demand Forecasting:
    
    - keywards: predict, forecast, demand, product, machine learning, deep learning


    ####{text}####

    Outout category and confidense using {format_instructions}

    """
    
    prompt_templete = ChatPromptTemplate.from_template(template=template_string)
    message = prompt_templete.format_messages(text=user_message, format_instructions=format_instructions)

    chat = OpenAI(temperature=0.1, base_url="http://localhost:1234/v1", api_key="not-needed", model="local-model")
    response = chat.invoke(message)
    result = output_parser.invoke(response)

    return result

# %% ../nbs/20autogen.ipynb 116
opening_message = """
Hello, I am FuturoFlow, the AI assistant for supply chain optimization. 🚀 \

FuturoFlow: An AI tool driving future-oriented supply chain processes. \

I respond to various challenges and questions regarding supply chain efficiency,  \
providing effective solutions and assisting in maximizing business outcomes.    \

Please tell us about the challenges or difficulties you are facing regarding your company's supply chain.
"""

vrp_message = """
Hello! We're eager to gain a better understanding of your delivery planning requirements. \\
To tailor our solutions effectively, could you please provide the following details:

Number of Time Windows:

- When considering deliveries to customers, how many time slots (time windows) are available for truck visits? \
For example, if the truck can visit between 10:00 AM to 12:00 PM and then between 1:00 PM to 3:00 PM with a break for lunch, you would have two time windows: [10:00, 12:00] and [13:00, 15:00].

Number of Dimensions of Cargo:

- How many units are used to determine if the cargo can be loaded onto the truck? \
For example, if you need to consider weight, volume, and quantity, the number of dimensions of the cargo would be 3.

Number of Skills:

- The concept of "skills" is used to represent the compatibility between customers (locations) and trucks (drivers) for delivery. \
If a truck does not possess all the skills required by a customer, it cannot handle that customer's delivery. \
For instance, if there are customers who can only accommodate trucks with a capacity of less than 10 tons, you would define a skill for trucks with a capacity of less than 10 tons and ensure that trucks with a capacity of 10 tons or more do not possess this skill. In this case, the number of skills would be 1. How many skills does your company anticipate needing?

Number of Breaks:

- How many breaks can a truck (driver) take? \
For example, if there is a possibility of taking breaks during lunch and dinner times, the number would be 2.
"""
